# Generated by Django 3.0.5 on 2020-05-03 10:24

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('athletes_limit', models.IntegerField(default=30)),
                ('bookings', models.IntegerField(default=0)),
                ('text', models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual Notes')),
                ('date', models.DateField(help_text='Day of the event', null=True, verbose_name='Day of the event')),
                ('start_time', models.TimeField(help_text='Starting time', null=True, verbose_name='Starting time')),
                ('end_time', models.TimeField(help_text='Final time', null=True, verbose_name='Final time')),
                ('ex_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxApp.Box')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.CharField(blank=True, max_length=500)),
                ('difficulty', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, upload_to='images/')),
                ('video_url', models.CharField(blank=True, max_length=100)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date published')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxApp.Box')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField(default=datetime.date.today)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxApp.Box')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tickets', models.IntegerField()),
                ('training_space', models.IntegerField()),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxApp.Box')),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boxApp.Training')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField(default=datetime.date.today)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxApp.Box')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
