# Generated by Django 2.2.8 on 2020-04-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=500)),
                ('difficulty', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=100)),
                ('video_url', models.CharField(max_length=100)),
                ('date_published', models.DateField(verbose_name='Date published')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=500)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('date_published', models.DateField(verbose_name='Date published')),
            ],
        ),
    ]
