# Generated by Django 3.0 on 2020-04-26 18:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boxApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='training',
            name='athletes_limit',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='training',
            name='bookings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='training',
            name='date',
            field=models.DateField(help_text='Day of the event', null=True, verbose_name='Day of the event'),
        ),
        migrations.AddField(
            model_name='training',
            name='ex_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='date_published',
            field=models.DateTimeField(null=True, verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='text',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='training',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='training',
            name='end_time',
            field=models.TimeField(help_text='Final time', null=True, verbose_name='Final time'),
        ),
        migrations.AlterField(
            model_name='training',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_time',
            field=models.TimeField(help_text='Starting time', null=True, verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='training',
            name='text',
            field=models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual Notes'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tickets', models.IntegerField()),
                ('training_space', models.IntegerField()),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boxApp.Training')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boxApp.User')),
            ],
        ),
    ]
