# Generated by Django 3.0.5 on 2020-04-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='img_url',
        ),
        migrations.AddField(
            model_name='exercise',
            name='img',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
