# Generated by Django 3.0.5 on 2020-04-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxApp', '0002_auto_20200430_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
