# Generated by Django 3.0.5 on 2020-05-04 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxApp', '0002_auto_20200504_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='Coach',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='boxApp.Coach'),
        ),
    ]
