# Generated by Django 3.0.5 on 2020-05-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxApp', '0003_athlete_coach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='Coach',
            new_name='coach',
        ),
    ]
