# Generated by Django 3.0.5 on 2020-05-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxApp', '0003_auto_20200430_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
