# Generated by Django 3.0.5 on 2020-05-04 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxApp', '0004_auto_20200504_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token', models.CharField(max_length=70)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxApp.Athlete')),
            ],
        ),
    ]
