# Generated by Django 3.0.5 on 2020-05-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxApp', '0005_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='Token',
            new_name='token',
        ),
    ]
